service: gbToolsAuthService

package:
  excludeDevDependencies: false

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies

custom:
  serverless-offline:
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  timeout: 30
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}

functions:
  login:
    handler: src/handlers/auth.login
    memorySize: 512
    events:
      - http:
          method: POST
          path: /login
          cors: true
  forgotPassword:
    handler: src/handlers/auth.forgotPassword
    memorySize: 256
    events:
      - http:
          method: POST
          path: /password/forgot
          cors: true
  resetPassword:
    handler: src/handlers/auth.resetPassword
    memorySize: 256
    events:
      - http:
          method: POST
          path: /password/reset
          cors: true
